### PR TITLE
symegine -> symengine, symengine-python

### PR DESCRIPTION
**Pull request by bjodah**
I've only tested this on linux but those tests pass:
- https://anaconda.org/bjodah/symengine/files
- https://anaconda.org/bjodah/symengine-python/files

### CODE REVIEW

**Comment by certik** [comment]
Thanks!

**Comment by bjodah** [comment]
FWIW, I am running into troubles with this on another machine (worked on my laptop and on my workstation):

```
                 import symengine
               File "/home/pysym/env/e1b02b5b86e6754c897d3302644a7f9d/lib/python2.7/site-packages/symengine/__init__.py", line 1, in <module>
                 from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
             ImportError: libgmpxx.so.4: cannot open shared object file: No such file or directory
```

cxx seems to be enabled here:
https://github.com/conda/conda-recipes/blob/master/gmp/build.sh

but not here (and I cannot find gmp-4 in `defaults` channel):
https://github.com/conda/conda-recipes/blob/master/gmp-4/build.sh

any clue @isuruf ?

**Comment by isuruf** [comment]
https://github.com/conda/conda-recipes/blob/master/gmp/build.sh doesn't enable `cxx` unless it is OSX, although your branch has a commit where it is enabled 
(see https://github.com/bjodah/conda-recipes/blob/csympy/gmp/build.sh#L5)

Can you retry after building gmp as well or try the binaries I uploaded, https://anaconda.org/isuruf ?

**Comment by bjodah** [comment]
@isuruf Oh yes, sorry - I got confused.
Building gmp from csympy branch and publishing in same channel gets me one step further.
But now glibcxx versions seem to mismatch:

```
                 from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
             ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pysym/env/e1b02b5b86e6754c897d3302644a7f9d/lib/python2.7/site-packages/symengine/lib/symengine_wrapper.so)
```

I believe this is because my workstation has GCC 4.9 and the other machine GCC 4.8 (both running Ubuntu 14.04).

I had some problems using `gcc` from conda's default channel before. Maybe those have been resolved by now and we can list gcc as a build dependency (and glibcxx as a run dependency)? 

Installing `symengine-python` from your channel has the same effect:

```
$ conda create -n isur python=3.4
$ source activate isur
(isur)bjorn@hera:~
$ source activate isur
$ conda install -c isuruf symengine-python
$ python3.4 -c 'import symengine'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bjorn/.conda/envs/isur/lib/python3.4/site-packages/symengine/__init__.py", line 1, in <module>
    from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/bjorn/.conda/envs/isur/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so)
```

Another thing I noticed when building the gmp recipe is that the configure script is quite aggressive by default with respect to tuning:

```
...
g++ -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../tests    -O2 -pedantic -fomit-frame-pointer -m64 -mtune=corei7 -march=corei7 -c -o t-mix.o t-mix.cc
...
```

note the `-march=corei7` which I believe has the risk of making the binary incompatible on processors lacking e.g. AVX and other instruction sets. Maybe we should set `amd64` for 64-bit builds and `i386` for 32-bit builds in gmp's build script (by [inspecting](http://conda.pydata.org/docs/building/environment-vars.html#environment-variables-set-during-the-build-process) `$ARCH`)?
https://gmplib.org/manual/Build-Options.html

**Comment by certik** [comment]
I don't have a solution regarding the glibc if we distribute binaries. But I thought conda allows to build from source, then there shouldn't be an issue, is there?

As to tuning, if we distribute binaries, then we can't assume AVX instructions, but if we allow compiling from source, then we should set it up that it compiles and works on all processors.

**Pull request merged**
